/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Metal Slug X)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80082A44u
#define func_80082A44 BootEntry  /* alias */
